# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96718c98705ec83467b8b9af7f0b9cb54708c425ff1aea3fa09e3e514021ea4858aecec77daf4a7a370ea8b1ac343cd6434c8ae565dfae47c8852b16836c4f3a

test:
  secret_key_base: 3b452fb0682290e66c2fcbf2675b0539c5d6500d1d79810ce2cdb28deb9fe2d7d26bbba837c9da53766c036cf160eeeefba3a26848db3ea7ea0fcee0b5656567

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
